services:
  nginx:
    image: nginx:latest
    container_name: paull
    volumes:
      - ./public:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - webnet

networks:
  webnet:
    external: false